-- Part 1

parseCode :: String -> Int -> Int -> Int

parseCode ('U':rest) x 0 = parseCode rest x 0
parseCode ('U':rest) x y = parseCode rest x (y - 1)
parseCode ('R':rest) 2 y = parseCode rest 2 y
parseCode ('R':rest) x y = parseCode rest (x + 1) y
parseCode ('D':rest) x 2 = parseCode rest x 2
parseCode ('D':rest) x y = parseCode rest x (y + 1)
parseCode ('L':rest) 0 y = parseCode rest 0 y
parseCode ('L':rest) x y = parseCode rest (x - 1) y
parseCode _ x y = (y * 3 + x) + 1

input = ["UUURRRRULRDLRDRRDURDDDLLDLLLULDUDDLDLULUURULRLDLRRLLLRRDRRLDDLLULUDUDDLRDRDUURDLURUURLRULLDDURULRRURDUURLULUUUURDDDDUUDLULRULLLRLLRRRURDLLRLLRRRUURULRDRUUDDDDDLLLRURRURRUURDUURDDRDLULRRLLLDRRRLURRLLURLDRRDDLDLRRLLRDRLLLLDLULDLRRDRRLDDURLULLUDLUDRRDRRLRLULURDRLRLUUUDLRLDLLLURDUDULULDDRUUURLLLDLLDDUDDRURURUDDLUULRDRRRRLDRDDURLUDURDULLDLUDLULDRLRLLRLLLLRURDURLLDRRDRLRUUUUULLLRUDURUDLLLUDLLLLRDLDRDUDRURLUDDUDDURLUUUUDDLLUDLULLLLLDUDLLRLRRDDDULULRLDRLLULDLUDLLURULRDDUURULRDLDLDLRL", "URUUURDULUDLUUUUDDRRRDRRRLDUDLRDRRDRDDLRUULDLLDUDULLLRLDRDRRLDLDLUUDRUULDUDULDUDURURDDURULDLURULRLULDUDDUULDLLLDDURDDRDDURUULUUDRLDDULDRRRRDURRUDLLLURDDDLRULLRDDRDDDDLUUDRDUULRRRRURULDDDLDDRDRRUDRRURUDRDDLDRRRLLURURUULUUDRDULLDRLRDRRDDURDUDLDRLUDRURDURURULDUUURDUULRRRRRUDLLULDDDRLULDDULUDRRRDDRUDRRDLDLRUULLLLRRDRRLUDRUULRDUDRDRRRDDRLLRUUDRLLLUDUDLULUUDULDRRRRDDRURULDULLURDLLLDUUDLLUDRLDURRRLDDDURUDUDURRULDD", "LRUDDULLLULRLUDUDUDRLLUUUULLUDLUUUUDULLUURDLLRDUDLRUDRUDDURURRURUDLLLRLDLUDRRRRRRDLUURLRDDDULRRUDRULRDRDDUULRDDLDULDRRRDDLURRURLLLRURDULLRUUUDDUDUURLRLDDUURLRDRRLURLDRLLUUURDRUUDUUUDRLURUUUDLDRRLRLLRRUURULLLRLLDLLLDULDDLDULDLDDRUDURDDURDUDURDLLLRRDDLULLLUDURLUDDLDLUUDRDRUDUUDLLDDLLLLDRDULRDLDULLRUDDUULDUDLDDDRUURLDRRLURRDDRUUDRUDLLDLULLULUDUDURDDRLRDLRLDRLDDRULLLRUDULDRLRLRULLRLLRRRLLRRRDDRULRUURRLLLRULDLUDRRDDLLLUDDUDDDLURLUDRDLURUUDLLDLULURRLLDURUDDDDRLULRDDLRLDDLRLLDDRRLRDUDUUULRRLRULUDURDUDRLRLRUDUDLLRRRRLRRUDUL", "RULLLLUUUDLLDLLRULLRURRULDDRDLUULDRLLRUDLLRRLRDURLLDUUUUURUUURDLUURRLDDDLRRRRLRULDUDDLURDRRUUDLRRRDLDDUDUDDRUDURURLDULLDLULDLLUDLULRDRLLURRLLDURLDLRDLULUDDULDLDDDDDUURRDRURLDLDULLURDLLDDLLUDLDLDRLRLDLRDRLDLRRUUDRURLUUUDLURUULDUDRDULLDURUDLUUURRRLLDUDUDDUUULLLRUULDLURUDDRLUDRDDLDLLUDUDRRRDDUUULUULLLRLLUURDUUDRUUULULLDLDRUUDURLLUULRLDLUURLLUUDRURDDRLURULDUDUUDRRUUURDULRLDUUDDRURURDRRULDDDRLUDLLUUDURRRLDLRLRDRURLURLLLRLDDLRRLDLDDURDUUDRDRRLDRLULDRLURUUUDDRLLLDDLDURLLLLDRDLDRRUDULURRLULRDRLLUULLRLRDRLLULUURRUDRUDDDLLDURURLURRRDLLDRDLUDRULULULRLDLRRRUUDLULDURLRDRLULRUUURRDDLRUURUDRURUDURURDD", "DURRDLLLDDLLDLLRLULULLRDLDRRDDRDLRULURRDUUDDRLLDDLDRRLRDUDRULDLRURDUUDRDDLLDRRDRUDUDULLDDDDLDRRRLRLRDRDLURRDDLDDDUUDRDRLLLDLUDDDLUULRDRLLLRLLUULUDDDRLDUUUURULRDDURRDRLUURLUDRLRLLLDDLRDDUULRRRRURDLDDDRLDLDRRLLDRDDUDDUURDLDUUDRDLDLDDULULUDDLRDDRLRLDDLUDLLDRLUDUDDRULLRLDLLRULRUURDDRDRDRURDRRLRDLLUDDRRDRRLDDULLLDLUDRRUDLDULDRURRDURLURRLDLRDLRUDLULUDDRULRLLDUURULURULURRLURRUULRULRRRLRDLULRLRLUDURDDRUUURDRLLRRRDDLDRRRULLDLRDRULDRRLRRDLUDDRDDDUUURRLULLDRRUULULLRRRRLDDRDDLUURLLUDLLDUDLULUULUDLLUUURRRUDDDRLLLRDRUUDUUURDRULURRLRDLLUURLRDURULDRRUDURRDDLDRLDRUUDRLLUDLRRU"]

-- Part 2

parseNewCode :: String -> Char -> Char

parseNewCode ('D':rest) '1' = parseNewCode rest '3'
parseNewCode ('R':rest) '2' = parseNewCode rest '3'
parseNewCode ('D':rest) '2' = parseNewCode rest '6'
parseNewCode ('U':rest) '3' = parseNewCode rest '1'
parseNewCode ('R':rest) '3' = parseNewCode rest '4'
parseNewCode ('D':rest) '3' = parseNewCode rest '7'
parseNewCode ('L':rest) '3' = parseNewCode rest '2'
parseNewCode ('D':rest) '4' = parseNewCode rest '8'
parseNewCode ('L':rest) '4' = parseNewCode rest '3'
parseNewCode ('R':rest) '5' = parseNewCode rest '6'
parseNewCode ('U':rest) '6' = parseNewCode rest '2'
parseNewCode ('R':rest) '6' = parseNewCode rest '7'
parseNewCode ('D':rest) '6' = parseNewCode rest 'A'
parseNewCode ('L':rest) '6' = parseNewCode rest '5'
parseNewCode ('U':rest) '7' = parseNewCode rest '3'
parseNewCode ('R':rest) '7' = parseNewCode rest '8'
parseNewCode ('D':rest) '7' = parseNewCode rest 'B'
parseNewCode ('L':rest) '7' = parseNewCode rest '6'
parseNewCode ('U':rest) '8' = parseNewCode rest '4'
parseNewCode ('R':rest) '8' = parseNewCode rest '9'
parseNewCode ('D':rest) '8' = parseNewCode rest 'C'
parseNewCode ('L':rest) '8' = parseNewCode rest '7'
parseNewCode ('L':rest) '9' = parseNewCode rest '8'
parseNewCode ('U':rest) 'A' = parseNewCode rest '6'
parseNewCode ('R':rest) 'A' = parseNewCode rest 'B'
parseNewCode ('U':rest) 'B' = parseNewCode rest '7'
parseNewCode ('R':rest) 'B' = parseNewCode rest 'C'
parseNewCode ('D':rest) 'B' = parseNewCode rest 'D'
parseNewCode ('L':rest) 'B' = parseNewCode rest 'A'
parseNewCode ('U':rest) 'C' = parseNewCode rest '8'
parseNewCode ('L':rest) 'C' = parseNewCode rest 'B'
parseNewCode ('U':rest) 'D' = parseNewCode rest 'B'
parseNewCode (_:rest) pos = parseNewCode rest pos
parseNewCode _ pos = pos